apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zkp-server-deploy
  name: zkp-server
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: zkp-server-deploy
status:
  loadBalancer: {}
