pub mod request_dto;
pub mod response_dto;

// public info
// Used when client is making the register commit
// r1 = g^k, r2 = h^k
// where k is a random seed generated by client
pub const G: u128 = 10;
pub const H: u128 = 20;
