name: publish zkp container images

on:
  #schedule:
  #  - cron: "00 13 * * *"
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
    # tags: ["v*.*.*"]

env:
  SERVER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/zkp-server
  CLIENT_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/zkp-client

jobs:
  build-and-push-server-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: set output for short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: build container Image
        run: |
          docker build . -f ./server/Dockerfile --tag $SERVER_IMAGE_NAME:latest --tag $SERVER_IMAGE_NAME:main-${{ steps.vars.outputs.sha_short }} --tag $SERVER_IMAGE_NAME:main-${{ github.run_number }}

      - name: push image to ghcr
        run: |
          docker push $SERVER_IMAGE_NAME:latest
          docker push $SERVER_IMAGE_NAME:main-${{ steps.vars.outputs.sha_short }}     
          docker push $SERVER_IMAGE_NAME:main-${{ github.run_number }}

  build-and-push-client-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: set output for short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: build container Image
        run: |
          docker build . -f ./client/Dockerfile --tag $CLIENT_IMAGE_NAME:latest --tag $CLIENT_IMAGE_NAME:main-${{ steps.vars.outputs.sha_short }} --tag $CLIENT_IMAGE_NAME:main-${{ github.run_number }}

      - name: push image to ghcr
        run: |
          docker images
          docker push $CLIENT_IMAGE_NAME:latest
          docker push $CLIENT_IMAGE_NAME:main-${{ steps.vars.outputs.sha_short }}     
          docker push $CLIENT_IMAGE_NAME:main-${{ github.run_number }}
