name: Integration Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
  schedule:
    - cron: "0 7,19 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: Run server
        run: docker run -d -p 9090:9090 ghcr.io/suren-m/zkp-server:latest
      - name: Run Integration tests        
        run: cargo test --test test_zkp_flow

