name: CI build and Unit Tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7,19 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: cargo build --release
      - name: Run unit tests
        id: unittests
        run: cargo test unittests -- --nocapture

      # publish results as a comment if workflow was a pull request
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Cargo Build ⚙️\`${{ steps.build.outcome }}\`            
            #### Cargo Tests 📖\`${{ steps.unittests.outcome }}\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
