name: Publish Docs

on:
  push:
    branches:
      - main  
    paths:
      - '!**/README.md'     
      
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clear existing docs
        run: rm -rf ./docs/*      
      - name: Generate Cargo Docs
        id: generate
        run: cargo doc --no-deps --release
      - name: Copy to docs dir
        run: cp -r ./target/doc/* ./docs/
      - name: Setup index and redirect        
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=zkp_server\">" > ./docs/index.html
      - name: commit
        run: |
          git config --global user.name 'workflow_action'
          git config --global user.email 'workflow_action@users.noreply.github.com'
          git add .
          git commit -m "docs: published from workflow"
          git push origin
    
      
      


